### ISSUE TITLE
Optional main parameters must be handled

### ISSUE THREAD

**Issue by MikelTolino** [MikelTolino/ft_irc#4]
`./ircserv [host:port_network:password_network] <port> <password>`
4
IRC Internet Relay Chat
◦ host is the hostname on which IRC must connect to join a already existing
network
◦ port_network is the server port on which IRC must connect on host
◦ password_network is the password needed to connect on host
◦ port is the port number on which your server will accept incoming connections.
◦ password is the password needed by any IRC client who wants to connect to
your server.
◦ If host, port_network and password_network aren’t given, you must create
a new IRC network

**Comment by mikevgb** [comment]
Server to server communication is not mandatory and is not implemented, so only port and password arguments will be handle.
