### ISSUE TITLE
End of /NAMES list

### ISSUE THREAD

**Issue by mikevgb** [MikelTolino/ft_irc#43]
Server should send a "End of /NAMES list" when connecting to a channel, ex:

:aoioaiori!ii@2f7.j18.j49ElA.virtual JOIN :#test00
:edinburgh.chathispano.com 353 aoioaiori @ #test00 :@oiaoaioaia aoioaiori
:edinburgh.chathispano.com 366 aoioaiori #test00 :End of /NAMES list.

**Comment by MikelTolino** [comment]
> If a client’s JOIN command to the server is successful, the server MUST send, in this order:
> 
> 1. A JOIN message with the client as the message <source> and the channel they have joined as the first parameter of the message.
> 2. The channel’s topic (with [RPL_TOPIC](https://modern.ircdocs.horse/#rpltopic-332) (332) and optionally [RPL_TOPICWHOTIME](https://modern.ircdocs.horse/#rpltopicwhotime-333) (333)), and no message if the channel does not have a topic.
> 3. A list of users currently joined to the channel (with one or more [RPL_NAMREPLY](https://modern.ircdocs.horse/#rplnamreply-353) (353) numerics followed by a single [RPL_ENDOFNAMES](https://modern.ircdocs.horse/#rplendofnames-366) (366) numeric). These RPL_NAMREPLY messages sent by the server MUST include the requesting client that has just joined the channel.

**RP_ENDOFNAMES** is not sending, so the solution is sending a new Reply with this content
