### ISSUE TITLE
Ban behaviour 

### ISSUE THREAD

**Issue by mikevgb** [MikelTolino/ft_irc#44]
Review how bans are set, ex:

:aoioaiori!ii@2f7.j18.j49ElA.virtual NICK :usuario2
:hola1234!i@2f7.j18.j49ElA.virtual MODE #test00 +b :usuario2!*@*
:hola1234!i@2f7.j18.j49ElA.virtual MODE #test00 -b :usuario2!*@*
:hola1234!i@2f7.j18.j49ElA.virtual MODE #test00 +b :erere!*@*

**Comment by MikelTolino** [comment]
This issue is not mandatory
